// middleware.js — place at project ROOT (same level as app/, package.json)
//
// ROUTE PATTERNS HANDLED:
//   A: /search-by-make/:make/parts/:parts
//   B: /search-by-make/:make/:model/:category/:subcategory        ← 410 logic (truth table)
//   C: /search-by-make/:make
//   D: /search-by-make/:make/:model                               ← always 200 if make valid
//   E: /search-by-make/:make/:model/:category/:subcategory/:slug  ← product slug pages
//
// TRUTH TABLE — Pattern B (/make/model/category/subcategory):
//
//  C# │ makeExcluded │ subcatValid │ seoTrue │ hasProduct │ result
//  ───┼──────────────┼─────────────┼─────────┼────────────┼──────────────
//  ✅ │ No           │ Yes         │ Yes     │ any        │ 200 (render)
//  ✅ │ any          │ any         │ any     │ Yes        │ 200 (product)
//  ───┼──────────────┼─────────────┼─────────┼────────────┼──────────────
//  C1 │ No           │ Yes         │ No      │ No         │ 410
//  C2 │ No           │ No          │ No      │ No         │ 410
//  C3 │ No           │ No          │ Yes     │ No         │ 410
//  C4 │ Yes          │ Yes         │ No      │ No         │ 410
//  C5 │ Yes          │ No          │ No      │ No         │ 410
//  C6 │ Yes          │ No          │ Yes     │ No         │ 410
//  C7 │ Yes          │ Yes         │ Yes     │ No         │ 410
//
// PATTERN E — Slug pages (/make/model/category/subcategory/slug):
//   Mirrors page logic:
//     const id = Number(slug.split("-").pop())
//     if (!product) notFound()       → 410
//     if (!compat)  notFound()       → 410 (make+model not in product compatibility)
//     else                           → 200

import { NextResponse } from 'next/server';

// Generated by: node scripts/generate-middleware-lookup.mjs
// Must exist before `next build`.
// Add to package.json: "prebuild": "node scripts/generate-middleware-lookup.mjs"
import { VALID_MAKES, MODEL_INDEX, PRODUCT_COMBOS, PRODUCT_IDS } from './lib/middleware-lookup';

// ─── Static data ──────────────────────────────────────────────────────────────

const EXCLUDED_MAKES = new Set([
    'Buick', 'Eagle', 'Lotus', 'Plymouth', 'Pontiac', 'Saab', 'Subaru',
    'Alfa Romeo', 'Geo', 'Oldsmobile', 'Isuzu', 'Saturn', 'Corbin', 'Holden',
    'Spyker', 'Spyker Cars', 'Aston Martin', 'Panoz', 'Foose', 'Morgan', 'Aptera',
    'Smart', 'SRT', 'Roush Performance', 'Pagani', 'Mobility Ventures LLC',
    'RUF Automobile', 'Koenigsegg', 'Karma', 'Polestar', 'STI', 'Kandi', 'Abarth',
    'Dorcen', 'Foton', 'W Motors', 'Opel', 'Skoda', 'Hillman', 'Austin', 'Fillmore',
    'Maybach', 'Merkur', 'Rambler', 'Shelby', 'Studebaker', 'Great Wall GWM',
    'Zeekr', 'ZNA', 'GAC', 'Gs7', 'Hongqi', 'W Motor', 'JAC', 'Jaecoo', 'Jetour',
    'TANK', 'Soueast', 'Zarooq Motors', 'Changan', 'Maxus', 'Haval', 'Zotye',
    'Sandstorm', 'Chery', 'Geely', 'BAIC', 'Bestune',
]);

const SELECTED_PARTS = [
    'Battery', 'Engine Assembly', 'Gearbox', 'Radiator',
    'AC Compressor', 'Alternator', 'Suspension', 'Shock Absorber',
    'Headlight Assembly', 'Bumpers', 'Brake Disc', 'Turbocharger',
    'Steering Rack', 'Water Pump', 'Fuel Pump', 'Starter',
    'Taillight', 'Axle Assembly', 'Lower Control Arm', 'Upper Control Arm',
    'Catalytic Convertor', 'AC Condenser', 'Wheel', 'Mirrors', 'Steering Box',
];

const SELECTED_PARTS_LC = new Set(SELECTED_PARTS.map(p => p.toLowerCase()));

// ─── URL patterns ─────────────────────────────────────────────────────────────
// IMPORTANT: Patterns are checked in order.
// E (5 segments) must be checked BEFORE B (4 segments) to avoid B
// accidentally matching the first 4 segments of a slug URL.

// A: /search-by-make/:make/parts/:parts
const MAKE_PARTS_RE = /^\/search-by-make\/([^/]+)\/parts\/([^/]+)\/?$/;

// E: /search-by-make/:make/:model/:category/:subcategory/:slug  (5 segments)
const SLUG_RE =
    /^\/search-by-make\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)\/?$/;

// B: /search-by-make/:make/:model/:category/:subcategory  (4 segments)
const MAKE_MODEL_CAT_SUBCAT_RE =
    /^\/search-by-make\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)\/?$/;

// D: /search-by-make/:make/:model  (2 segments)
const MAKE_MODEL_RE = /^\/search-by-make\/([^/]+)\/([^/]+)\/?$/;

// C: /search-by-make/:make  (1 segment)
const MAKE_ONLY_RE = /^\/search-by-make\/([^/]+)\/?$/;

// ─── Blocked bots ─────────────────────────────────────────────────────────────

const BLOCKED_BOTS =
    /blexbot|serpstatbot|dataforseobot|dotbot|petalbot|magpie-crawler|rogerbot|mj12bot|seekbotbytespider|baiduspider|yisouspider|sogouspider|haosouspider|scooter|shenma|qwen|ernie|kimi|doubao|deepseek|youdaobot|toutiaospider/i;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function gone() {
    return new NextResponse(null, {
        status: 410,
        headers: { 'Cache-Control': 'public, max-age=86400' },
    });
}

function redirect301(destination) {
    return NextResponse.redirect(destination, { status: 301 });
}

// ─── Middleware ───────────────────────────────────────────────────────────────

export function middleware(request) {
    const { pathname } = request.nextUrl;
    const ua = request.headers.get('user-agent') || '';

    // Bot check — runs first
    if (BLOCKED_BOTS.test(ua)) {
        return new NextResponse('Access Denied', { status: 403 });
    }

    if (!pathname.startsWith('/search-by-make/')) return NextResponse.next();

    // ── Pattern A: /search-by-make/:make/parts/:parts ─────────────────────────
    const matchA = pathname.match(MAKE_PARTS_RE);
    if (matchA) {
        const make = decodeURIComponent(matchA[1]).trim();
        const parts = decodeURIComponent(matchA[2]).trim();

        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();
        if (!SELECTED_PARTS_LC.has(parts.toLowerCase())) return gone();

        // 301 if wrong casing
        const canonicalPart = SELECTED_PARTS.find(
            p => p.toLowerCase() === parts.toLowerCase()
        );
        if (canonicalPart && canonicalPart !== parts) {
            const url = request.nextUrl.clone();
            url.pathname = `/search-by-make/${encodeURIComponent(make)}/parts/${encodeURIComponent(canonicalPart)}`;
            return redirect301(url.toString());
        }

        return NextResponse.next();
    }

    // ── Pattern E: /search-by-make/:make/:model/:category/:subcategory/:slug ───
    // Checked BEFORE Pattern B — 5 segments vs 4 segments
    // Mirrors page logic:
    //   const id = Number(slug.split("-").pop())
    //   const product = products.find(p => p.id === id)  → !product = notFound
    //   const compat = product.compatibility?.find(       → !compat  = notFound
    //     c => c.make === make && c.model === model
    //   )
    const matchE = pathname.match(SLUG_RE);
    if (matchE) {
        const make = decodeURIComponent(matchE[1]).trim();
        const model = decodeURIComponent(matchE[2]).trim();
        const slug = decodeURIComponent(matchE[5]).trim();

        // Extract id from end of slug — mirrors: slug.split("-").pop()
        const slugParts = slug.split('-');
        const id = Number(slugParts[slugParts.length - 1]);

        // Invalid id (NaN or 0) → 410
        if (!id) return gone();

        // Product doesn't exist → 410
        const compatList = PRODUCT_IDS[id];
        if (!compatList) return gone();

        // make+model not in this product's compatibility → 410
        const comboKey = `${make.toLowerCase()}|${model.toLowerCase()}`;
        if (!compatList.includes(comboKey)) return gone();

        return NextResponse.next(); // ✅ 200
    }

    // ── Pattern B: /search-by-make/:make/:model/:category/:subcategory ─────────
    const matchB = pathname.match(MAKE_MODEL_CAT_SUBCAT_RE);
    if (matchB) {
        const make = decodeURIComponent(matchB[1]).trim();
        const model = decodeURIComponent(matchB[2]).trim();
        const category = decodeURIComponent(matchB[3]).trim();
        const subcategory = decodeURIComponent(matchB[4]).trim();

        const makeLc = make.toLowerCase();
        const modelLc = model.toLowerCase();
        const catLc = category.toLowerCase();
        const subLc = subcategory.toLowerCase();

        const makeExcluded = EXCLUDED_MAKES.has(make);
        const makeExists = VALID_MAKES.has(makeLc);

        if (!makeExists && !makeExcluded) return gone();

        const subcatValid = SELECTED_PARTS_LC.has(subLc);
        const seoTrue = MODEL_INDEX[`${makeLc}|${modelLc}`] === 1;

        const shouldRender = !makeExcluded && subcatValid && seoTrue;
        if (shouldRender) return NextResponse.next(); // ✅ 200

        const productKey = `${makeLc}|${modelLc}|${catLc}|${subLc}`;
        if (PRODUCT_COMBOS.has(productKey)) return NextResponse.next(); // ✅ 200

        return gone(); // ❌ 410 — covers C1–C7
    }

    // ── Pattern C: /search-by-make/:make ──────────────────────────────────────
    const matchC = pathname.match(MAKE_ONLY_RE);
    if (matchC) {
        const make = decodeURIComponent(matchC[1]).trim();
        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();
        return NextResponse.next();
    }

    // ── Pattern D: /search-by-make/:make/:model ────────────────────────────────
    // seo flag intentionally NOT checked — model pages always render
    const matchD = pathname.match(MAKE_MODEL_RE);
    if (matchD) {
        const make = decodeURIComponent(matchD[1]).trim();
        const model = decodeURIComponent(matchD[2]).trim();

        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();

        // Model must exist in CarData (seo value irrelevant)
        const key = `${make.toLowerCase()}|${model.toLowerCase()}`;
        if (MODEL_INDEX[key] === undefined) return gone();

        return NextResponse.next(); // ✅ 200 — seo:true or seo:false both pass
    }

    // Any other /search-by-make/* shape → 410
    return gone();
}

export const config = {
    matcher: ['/search-by-make/:path*'],
};