name = "auto-parts"
account_id= "99113cb9b96fa604e4bae5c1e838ef1a"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
